In [1]:
from pathlib import Path

import pandas as pd
pd.options.mode.chained_assignment = None
import numpy as np

import numbers

In [22]:
INITIAL_PATH = Path.cwd().parent
DATA_PATH = INITIAL_PATH / 'data'
INITIAL_DATA_PATH = DATA_PATH / 'initial'

In [23]:
INITIAL_KLEKOTA_ROTH_DATA = INITIAL_DATA_PATH / 'cardiotoxicity_hERG_KlekFP_ready_set.csv'
INITIAL_MACCS_DATA = INITIAL_DATA_PATH / 'cardiotoxicity_hERG_MACCSFP_ready_set.csv'
INITIAL_EXT_DATA = INITIAL_DATA_PATH / 'cardiotoxicity_hERG_ExtFP_ready_set.csv'

In [25]:
klekota_roth_df = pd.read_csv(INITIAL_KLEKOTA_ROTH_DATA)
klekota_roth_df.sample(10)

C:\Users\SG0306249\Miniconda3\envs\cardiotoxicity_prediction\lib\site-packages\IPython\core\interactiveshell.py:3444: DtypeWarning: Columns (0) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,IC50,KRFP1,KRFP2,KRFP3,KRFP4,KRFP5,KRFP6,KRFP7,KRFP8,KRFP9,...,KRFP4851,KRFP4852,KRFP4853,KRFP4854,KRFP4855,KRFP4856,KRFP4857,KRFP4858,KRFP4859,KRFP4860
10,24330.0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3367,31622.78,1,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
8463,22000.0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1413,1.0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8109,22400.0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6281,60000.0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8358,143.0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6071,36400.0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5295,11600.0,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5098,290.0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [26]:
print(f'Number of rows: {klekota_roth_df.shape[0]}\nNumber of cols: {klekota_roth_df.shape[1]}')

Number of rows: 11504
Number of cols: 4861

In [27]:
def is_float(value):
    try:
        float(value)
        return True
    except:
        return False
    
klekota_roth_df[klekota_roth_df['IC50'].apply(lambda value: not(is_float(value)))]

,IC50,KRFP1,KRFP2,KRFP3,KRFP4,KRFP5,KRFP6,KRFP7,KRFP8,KRFP9,...,KRFP4851,KRFP4852,KRFP4853,KRFP4854,KRFP4855,KRFP4856,KRFP4857,KRFP4858,KRFP4859,KRFP4860
15,'=',1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16,'=',1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29,'=',1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
30,27}]TRIACONTA-8,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
43,'=',1,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11421,'=',1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11454,'=',1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11480,'=',1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11482,'>',1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11483,'>',1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [28]:
klekota_roth_df = klekota_roth_df[klekota_roth_df['IC50'].apply(is_float)]

In [29]:
klekota_roth_df['IC50'] = klekota_roth_df['IC50'].astype('float64') 
klekota_roth_df[1:] = klekota_roth_df[1:].astype('int')

In [30]:
klekota_roth_df.apply(lambda col: col.unique())

IC50        [645.0, 6600.0, 1600.0, 6700.0, 21400.0, 20800...
KRFP1                                                  [0, 1]
KRFP2                                                  [0, 1]
KRFP3                                                  [0, 1]
KRFP4                                                     [0]
                                  ...
KRFP4856                                               [0, 1]
KRFP4857                                               [0, 1]
KRFP4858                                               [0, 1]
KRFP4859                                                  [0]
KRFP4860                                                  [0]
Length: 4861, dtype: object

In [31]:
columns_without_difference = [k for k,v in klekota_roth_df.apply(lambda col: col.unique()).apply(lambda x: len(x) == 1).items() if v]

len(columns_without_difference)

2760

In [32]:
klekota_roth_df = klekota_roth_df.drop(columns=columns_without_difference)

In [33]:
klekota_roth_df.apply(lambda col: col.unique()).sample(10)

KRFP3520    [0, 1]
KRFP3925    [0, 1]
KRFP3008    [0, 1]
KRFP3082    [0, 1]
KRFP310     [0, 1]
KRFP56      [0, 1]
KRFP3753    [0, 1]
KRFP3001    [0, 1]
KRFP3814    [0, 1]
KRFP2025    [0, 1]
dtype: object

In [34]:
def calculate_if_toxic(row):
    if row['IC50'] < 10000:
        return 1
    return 0
klekota_roth_df['toxic'] = klekota_roth_df.apply(calculate_if_toxic, axis=1)
klekota_roth_df['toxic'].value_counts()

0    5389
1    5246
Name: toxic, dtype: int64